apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: golang-vs-api-demo
data:
  HTTP_ADDR: ":8080"
  LOG_LEVEL: "info"
  APP_ENV: "k3d"
  MIGRATIONS_DIR: "/migrations"
  POSTGRES_DB: "todo"
  POSTGRES_USER: "todo"
